require "user.plugins"
require "user.basic_config"
require "user.keymaps"
require "user.telescope"
require "user.surround"
require "user.which_keys"
require "user.neo_scroll"
require "user.lab"
require "user.harpoon"
require "user.lsp-hints"
require "user.autocommands"
require "user.copilot"
require "user.dial"
-- TODO: add more feature
